version: '2.1'
services:
  trudesk:
    image: polonel/trudesk:1  # Usa a imagem original, pois vamos sobrepor com bind
    restart: always
    ports:
      - "8118:8118"
    dns:
      - "1.1.1.1"
      - "8.8.8.8"
    environment:
      NODE_ENV: production  # Ou mude para 'development' se quiser modo dev no app
      TRUDESK_DOCKER: "true"
      TD_MONGODB_SERVER: mongo
      TD_MONGODB_DATABASE: trudesk
      USE_XFORWARDIP: "true"
      ELASTICSEARCH_URI: http://elasticsearch:9200
    volumes:
      - ./:/usr/src/trudesk  # Bind mount: Monta o diret√≥rio local (.) no path interno do container
      - trudesk_uploads:/usr/src/trudesk/public/uploads
      - trudesk_backups:/usr/src/trudesk/backups
    #command: sh -c "yarn install && yarn build && node ./app"  # Executa install, build e depois inicia o app
  mongo:
    image: mongo:5.0-focal
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo:/var/lib/mongo
      - mongo_data:/data/db:rw
  elasticsearch:
    image: elasticsearch:8.0.0
    restart: always
    environment:
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false
      - discovery.type=single-node
      - bootstrap.memory_lock=true
    mem_limit: 1073741824
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data
volumes:
  trudesk_uploads:
  trudesk_backups:
  mongo:
  mongo_data:
  elasticsearch: